import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { passwordReset, verifyEmail } from "@/lib/email/messages";
import { sendEmail } from "@/lib/email/send";
import { TRIAL_DAYS } from "@/lib/plans";
import { referrerFromCookieHeader } from "@/lib/referrals";
import { leads } from "@/db/schema";
import { sourceFromCookieHeader } from "@/lib/leads";
import { answersFromCookieHeader } from "@/lib/quiz";

// Server-side auth setup. BETTER_AUTH_SECRET and BETTER_AUTH_URL are read
// from web/.env automatically.
export const auth = betterAuth({
  appName: "PhotoEZ Cloud",
  database: drizzleAdapter(db, { provider: "pg", schema }),
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 10,
    // "Forgot password?": emails a one-hour link to /reset-password.
    sendResetPassword: async ({ user, url }) => {
      await sendEmail({
        photographerId: user.id,
        kind: "password_reset",
        to: user.email,
        content: passwordReset(user.name, url),
        fromName: "PhotoEZ Cloud",
        studioName: "PhotoEZ Cloud",
        footer: "PhotoEZ Cloud account email.",
      });
    },
    // A reset signs out every other browser, in case someone else was in.
    revokeSessionsOnPasswordReset: true,
    // New studios confirm their email before they can log in.
    requireEmailVerification: true,
  },
  // The confirmation email: sent at sign-up, and again if an unconfirmed
  // studio tries to log in. The link signs them in.
  emailVerification: {
    sendOnSignUp: true,
    sendOnSignIn: true,
    autoSignInAfterVerification: true,
    expiresIn: 24 * 60 * 60,
    sendVerificationEmail: async ({ user, url }) => {
      await sendEmail({
        photographerId: user.id,
        kind: "email_verification",
        to: user.email,
        content: verifyEmail(user.name, url),
        fromName: "PhotoEZ Cloud",
        studioName: "PhotoEZ Cloud",
        footer: "PhotoEZ Cloud account email.",
      });
    },
  },
  // Point Better Auth's built-in models at our table names.
  user: {
    modelName: "photographers",
    additionalFields: {
      businessName: { type: "string", required: false },
      // Set below on sign-up; never taken from the sign-up form.
      trialEndsAt: { type: "date", required: false, input: false },
      referredById: { type: "string", required: false, input: false },
    },
  },
  // Every new studio starts with a free Pro trial (lib/plans.ts), and
  // remembers who referred it, from the /r link's cookie (lib/referrals.ts).
  databaseHooks: {
    user: {
      create: {
        before: async (user, context) => ({
          data: {
            ...user,
            trialEndsAt: new Date(Date.now() + TRIAL_DAYS * 24 * 60 * 60 * 1000),
            referredById: await referrerFromCookieHeader(context?.headers?.get("cookie")).catch(() => null),
          },
        }),
        // Where the new studio came from (the landing page's ?src=, kept in
        // a cookie by the sign-up page), for Settings > Sign-ups. Works for
        // email and Google sign-ups alike; never holds sign-up up.
        after: async (user, context) => {
          const cookie = context?.headers?.get("cookie");
          const source = sourceFromCookieHeader(cookie);
          // And their quiz answers, if they took the quiz (app/quiz).
          const quiz = answersFromCookieHeader(cookie);
          if (!source && !quiz) return;
          await db
            .insert(leads)
            .values({ email: user.email.toLowerCase(), source, quiz })
            .onConflictDoNothing({ target: leads.email })
            .catch(() => undefined);
        },
      },
    },
  },
  // "Continue with Google", when its keys are in .env (GOOGLE_CLIENT_ID and
  // GOOGLE_CLIENT_SECRET, from the Google Cloud project's OAuth client).
  socialProviders:
    process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
      ? { google: { clientId: process.env.GOOGLE_CLIENT_ID, clientSecret: process.env.GOOGLE_CLIENT_SECRET } }
      : {},
  session: { modelName: "sessions" },
  account: {
    modelName: "accounts",
    // Google confirms the address, so signing in with Google opens the
    // account already using that email (signed up with a password) instead
    // of making a second one.
    accountLinking: { enabled: true, trustedProviders: ["google"] },
  },
  verification: { modelName: "verifications" },
  advanced: {
    // Our tables use UUID ids generated by Postgres.
    database: { generateId: "uuid" },
  },
  // Lets server actions set the session cookie. Must be the last plugin.
  plugins: [nextCookies()],
});
