import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { db } from "@/db";
import * as schema from "@/db/schema";

// Server-side auth setup. BETTER_AUTH_SECRET and BETTER_AUTH_URL are read
// from web/.env automatically.
export const auth = betterAuth({
  appName: "PhotoEZ Cloud",
  database: drizzleAdapter(db, { provider: "pg", schema }),
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 10,
  },
  // Point Better Auth's built-in models at our table names.
  user: {
    modelName: "photographers",
    additionalFields: {
      businessName: { type: "string", required: false },
    },
  },
  session: { modelName: "sessions" },
  account: { modelName: "accounts" },
  verification: { modelName: "verifications" },
  advanced: {
    // Our tables use UUID ids generated by Postgres.
    database: { generateId: "uuid" },
  },
  // Lets server actions set the session cookie. Must be the last plugin.
  plugins: [nextCookies()],
});
