import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { passwordReset } from "@/lib/email/messages";
import { sendEmail } from "@/lib/email/send";

// Server-side auth setup. BETTER_AUTH_SECRET and BETTER_AUTH_URL are read
// from web/.env automatically.
export const auth = betterAuth({
  appName: "PhotoEZ Cloud",
  database: drizzleAdapter(db, { provider: "pg", schema }),
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 10,
    // "Forgot password?": emails a one-hour link to /reset-password.
    sendResetPassword: async ({ user, url }) => {
      await sendEmail({
        photographerId: user.id,
        kind: "password_reset",
        to: user.email,
        content: passwordReset(user.name, url),
        fromName: "PhotoEZ Cloud",
        studioName: "PhotoEZ Cloud",
        footer: "PhotoEZ Cloud account email.",
      });
    },
    // A reset signs out every other browser, in case someone else was in.
    revokeSessionsOnPasswordReset: true,
  },
  // Point Better Auth's built-in models at our table names.
  user: {
    modelName: "photographers",
    additionalFields: {
      businessName: { type: "string", required: false },
    },
  },
  session: { modelName: "sessions" },
  account: { modelName: "accounts" },
  verification: { modelName: "verifications" },
  advanced: {
    // Our tables use UUID ids generated by Postgres.
    database: { generateId: "uuid" },
  },
  // Lets server actions set the session cookie. Must be the last plugin.
  plugins: [nextCookies()],
});
